name: Build OpenVario Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        machine:
          - ov-cb2-ch57
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Build Container
        run: |
          docker pull ghcr.io/openvario/ovbuild-container:latest

      - name: Build Yocto Image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v /yocto-cache/downloads:/workspace/downloads \
            -v /yocto-cache/sstate:/workspace/sstate \
            -w /workspace \
            ghcr.io/openvario/ovbuild-container:latest \
            bash -c '
              ls
              source openembedded-core/oe-init-build-env .
              ls
              sed -i "/^MACHINE/d" conf/local.conf
              echo "MACHINE = \"${{ matrix.machine }}\"" >> conf/local.conf
              more conf/local.conf

              bitbake openvario-image
            '

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openvario-image-${{ matrix.machine }}
          path: |
            tmp/deploy/images/**
