name: Build OpenVario Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        machine:
          - ov-cb2-ch57
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Verify checkout
        run: |
          ls -la
          ls -la openembedded-core
      
      - name: Pull Build Container
        run: |
          docker pull ghcr.io/openvario/ovbuild-container:latest

      - name: Build Yocto Image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workdir \
            -v /yocto-cache/downloads:/workdir/downloads \
            -v /yocto-cache/sstate:/workdir/sstate \
            -w /workdir \
            ghcr.io/openvario/ovbuild-container:latest \
            bash -c '
              pwd
              id
              
              source openembedded-core/oe-init-build-env .
              
              pwd 
              ls -al
              
              sed -i "/^MACHINE/d" conf/local.conf
              echo "MACHINE = \"${{ matrix.machine }}\"" >> conf/local.conf
              
              more conf/local.conf

              bitbake openvario-image
            '

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openvario-image-${{ matrix.machine }}
          path: |
            tmp/deploy/images/**
